# Generated by Django 4.2 on 2023-12-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banglorejobs',
            old_name='phonenum',
            new_name='contactnumber',
        ),
        migrations.RenameField(
            model_name='banglorejobs',
            old_name='address',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='banglorejobs',
            old_name='title',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='hydjobs',
            old_name='phonenum',
            new_name='contactnumber',
        ),
        migrations.RenameField(
            model_name='hydjobs',
            old_name='address',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='hydjobs',
            old_name='title',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='punejobs',
            old_name='phonenum',
            new_name='contactnumber',
        ),
        migrations.RenameField(
            model_name='punejobs',
            old_name='address',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='punejobs',
            old_name='title',
            new_name='role',
        ),
    ]
