# Generated by Django 4.2 on 2023-12-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_rename_phonenum_banglorejobs_contactnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banglorejobs',
            name='location',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='location',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='location',
            field=models.CharField(max_length=65),
        ),
    ]
